name: mycampusinfo_app
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.10.0-290.4.beta

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  pretty_dio_logger: ^1.4.0
  dartz: ^0.10.1
  firebase_auth: ^5.6.2
  firebase_core: ^3.15.1
  google_sign_in: ^7.1.1
  google_sign_in_web: ^1.0.0
  firebase_messaging: ^15.2.9
  flutter_local_notifications: ^19.3.1
  shared_preferences: ^2.5.3
  go_router: ^16.2.0
  provider: ^6.1.5+1
  stylish_bottom_bar: ^1.1.1
  url_launcher: ^6.3.2
  freezed_annotation: ^3.1.0
  permission_handler: ^12.0.1
  json_annotation: ^4.9.0
  timeago: ^3.6.1
  freezed: ^3.2.0
  json_serializable: ^6.10.0
  get_it: ^8.2.0
  flutter_secure_storage: ^9.2.4
  visibility_detector: ^0.4.0+2
  intl: ^0.20.2
  lottie: ^3.3.2
  flutter_pdfview: ^1.3.2
  path_provider: ^2.1.4
  geolocator: ^11.0.0
  geocoding: ^3.0.0
  device_preview: ^1.3.1
  connectivity_plus: ^7.0.0
  http: ^1.5.0
  easy_debounce: ^2.0.3
  change_app_package_name: ^1.5.0
  razorpay_flutter: ^1.4.0
  dtd: ^4.0.0
  flutter_lints: ^6.0.0
  google_fonts: ^6.3.3
  json_rpc_2: ^4.0.0
  path: ^1.9.1
  stack_trace: ^1.12.1
  web: ^1.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.7.0
  flutter_gen_runner: ^5.11.0

flutter:
  uses-material-design: true

  assets:
     - assets/images/
     - assets/animations/
     - assets/icons/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/poppins/Poppins-ExtraBold.ttf
          weight: 800

    - family: Barlow
      fonts:
        - asset: assets/fonts/barlow/BarlowCondensed-Thin.ttf
          weight: 100
        - asset: assets/fonts/barlow/BarlowCondensed-Regular.ttf
          weight: 400
        - asset: assets/fonts/barlow/BarlowCondensed-Medium.ttf
          weight: 500
        - asset: assets/fonts/barlow/BarlowCondensed-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/barlow/BarlowCondensed-Bold.ttf
          weight: 700
        - asset: assets/fonts/barlow/BarlowCondensed-ExtraBold.ttf
          weight: 800

    - family: Saira
      fonts:
        - asset: assets/fonts/saira/Saira-Thin.ttf
          weight: 100
        - asset: assets/fonts/saira/Saira-Regular.ttf
          weight: 400
        - asset: assets/fonts/saira/Saira-Medium.ttf
          weight: 500
        - asset: assets/fonts/saira/Saira-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/saira/Saira-Bold.ttf
          weight: 700
        - asset: assets/fonts/saira/Saira-ExtraBold.ttf
          weight: 800